[[redirects]]
  from = "http://sangorkglobal.com/*"
  to = "https://www.sangorkglobal.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://sangorkglobal.com/*"
  to = "https://www.sangorkglobal.com/:splat"
  status = 301
  force = true
