[[redirects]]
  from = "http://sangork.com/*"
  to = "https://www.sangork.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://sangork.com/*"
  to = "https://www.sangork.com/:splat"
  status = 301
  force = true
